plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kaizen.print'
    compileSdk 33

    defaultConfig {
        applicationId "com.kaizen.print"
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName "0.1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation files('libs/neptune-lite-api.jar')
}
